/**
 * TV Show & Episode Database — Classic Television 1970–2000
 * Content is sourced from publicly available archives.
 */

const SHOWS = [
  /* ────────────────────────────────────────────────────────────
     DUE SOUTH  (1994–1998)
     Archive identifier: due-south-1994-98
     Individual episodes addressed via the ?index= playlist param.
     Pilot = index 0; Season 1 episodes = index 1–22, etc.
     ──────────────────────────────────────────────────────────── */
  {
    id: "due-south",
    title: "Due South",
    years: "1994–1998",
    genre: ["Drama", "Comedy", "Crime"],
    rating: "TV-PG",
    score: 8.2,
    description:
      "A straight-laced Canadian Mountie, Constable Benton Fraser, is posted to the Canadian Consulate in Chicago where he teams up with the rough-around-the-edges Det. Ray Vecchio to solve crimes with charm, integrity, and a deaf wolf.",
    thumbnail: "https://archive.org/services/img/due-south-1994-98",
    featured: true,
    episodes: [
      /* ── Pilot ── */
      {
        id: "ds-s00e01", title: "Pilot", season: 0, episode: 1,
        year: 1994, duration: "90 min",
        description: "Mountie Benton Fraser arrives in Chicago to investigate his father's death and ends up teaming with Det. Ray Vecchio.",
        archiveId: "due-south-1994-98", archiveIndex: 0,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      /* ── Season 1 ── */
      {
        id: "ds-s01e01", title: "Free Willie", season: 1, episode: 1,
        year: 1994, duration: "47 min",
        description: "Fraser helps free a wrongly convicted man and uncovers a corporate cover-up.",
        archiveId: "due-south-1994-98", archiveIndex: 1,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e02", title: "Diefenbaker's Day Off", season: 1, episode: 2,
        year: 1994, duration: "47 min",
        description: "Diefenbaker, Fraser's deaf wolf, witnesses a murder while Fraser is stuck at the Consulate.",
        archiveId: "due-south-1994-98", archiveIndex: 2,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e03", title: "Manhunt", season: 1, episode: 3,
        year: 1994, duration: "47 min",
        description: "Fraser tracks a fugitive from his past across Chicago.",
        archiveId: "due-south-1994-98", archiveIndex: 3,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e04", title: "They Eat Horses, Don't They?", season: 1, episode: 4,
        year: 1994, duration: "47 min",
        description: "Fraser and Vecchio investigate the theft of a prize racehorse.",
        archiveId: "due-south-1994-98", archiveIndex: 4,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e05", title: "Pizzas and Promises", season: 1, episode: 5,
        year: 1994, duration: "47 min",
        description: "A seemingly routine pizza delivery turns into a case involving the mob.",
        archiveId: "due-south-1994-98", archiveIndex: 5,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e06", title: "Chinatown", season: 1, episode: 6,
        year: 1994, duration: "47 min",
        description: "Fraser and Vecchio are drawn into Chicago's Chinatown to solve a kidnapping.",
        archiveId: "due-south-1994-98", archiveIndex: 6,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e07", title: "Chicago Holiday (Part 1)", season: 1, episode: 7,
        year: 1994, duration: "47 min",
        description: "Fraser escorts a European princess around Chicago, unaware that assassins are on her trail.",
        archiveId: "due-south-1994-98", archiveIndex: 7,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e08", title: "Chicago Holiday (Part 2)", season: 1, episode: 8,
        year: 1994, duration: "47 min",
        description: "Fraser and Vecchio race to protect the princess from the assassins closing in on her.",
        archiveId: "due-south-1994-98", archiveIndex: 8,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e09", title: "A Cop, a Mountie and a Baby", season: 1, episode: 9,
        year: 1994, duration: "47 min",
        description: "Fraser and Vecchio must look after an abandoned baby while solving a case.",
        archiveId: "due-south-1994-98", archiveIndex: 9,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e10", title: "The Gift of the Wheelman", season: 1, episode: 10,
        year: 1994, duration: "47 min",
        description: "A getaway driver seeks Fraser's help after becoming involved in a bank robbery.",
        archiveId: "due-south-1994-98", archiveIndex: 10,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e11", title: "You Must Remember This", season: 1, episode: 11,
        year: 1994, duration: "47 min",
        description: "A woman with amnesia holds the key to a dangerous secret.",
        archiveId: "due-south-1994-98", archiveIndex: 11,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e12", title: "A Hawk and a Handsaw", season: 1, episode: 12,
        year: 1994, duration: "47 min",
        description: "Fraser is involuntarily committed to a psychiatric hospital and must unravel a plot from within.",
        archiveId: "due-south-1994-98", archiveIndex: 12,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e13", title: "An Eye for an Eye", season: 1, episode: 13,
        year: 1994, duration: "47 min",
        description: "Fraser investigates a case of apparent vigilante justice in a neighbourhood under siege.",
        archiveId: "due-south-1994-98", archiveIndex: 13,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e14", title: "The Man Who Knew Too Little", season: 1, episode: 14,
        year: 1994, duration: "47 min",
        description: "An innocent bystander witnesses a crime but doesn't realise what he saw.",
        archiveId: "due-south-1994-98", archiveIndex: 14,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e15", title: "The Wild Bunch", season: 1, episode: 15,
        year: 1994, duration: "47 min",
        description: "Fraser and Vecchio tangle with a gang of elderly bank robbers.",
        archiveId: "due-south-1994-98", archiveIndex: 15,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e16", title: "The Blue Line", season: 1, episode: 16,
        year: 1994, duration: "47 min",
        description: "An NHL hockey player is implicated in a crime and Fraser uses his knowledge of the game to help.",
        archiveId: "due-south-1994-98", archiveIndex: 16,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e17", title: "The Deal", season: 1, episode: 17,
        year: 1994, duration: "47 min",
        description: "Fraser and Vecchio must negotiate a dangerous hostage situation.",
        archiveId: "due-south-1994-98", archiveIndex: 17,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e18", title: "An Invitation to Romance", season: 1, episode: 18,
        year: 1994, duration: "47 min",
        description: "Fraser's courtly manners attract the attention of a lonely widow hiding a dark secret.",
        archiveId: "due-south-1994-98", archiveIndex: 18,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e19", title: "Heaven and Earth", season: 1, episode: 19,
        year: 1995, duration: "47 min",
        description: "Fraser receives a spiritual visit and must solve a decades-old murder mystery.",
        archiveId: "due-south-1994-98", archiveIndex: 19,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e20", title: "Victoria's Secret (Part 1)", season: 1, episode: 20,
        year: 1995, duration: "47 min",
        description: "A woman from Fraser's past resurfaces in Chicago, reopening old wounds and old cases.",
        archiveId: "due-south-1994-98", archiveIndex: 20,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e21", title: "Victoria's Secret (Part 2)", season: 1, episode: 21,
        year: 1995, duration: "47 min",
        description: "Fraser's loyalty is torn between his duty and the woman he once loved.",
        archiveId: "due-south-1994-98", archiveIndex: 21,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s01e22", title: "Letting Go", season: 1, episode: 22,
        year: 1995, duration: "47 min",
        description: "Fraser struggles to move on in the aftermath of Victoria's departure.",
        archiveId: "due-south-1994-98", archiveIndex: 22,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      /* ── Season 2 ── */
      {
        id: "ds-s02e01", title: "North", season: 2, episode: 1,
        year: 1995, duration: "47 min",
        description: "Fraser heads north to investigate a murder in Canada's wilderness.",
        archiveId: "due-south-1994-98", archiveIndex: 23,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e02", title: "Vault", season: 2, episode: 2,
        year: 1995, duration: "47 min",
        description: "Fraser and Vecchio are trapped inside a bank vault during a robbery.",
        archiveId: "due-south-1994-98", archiveIndex: 24,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e03", title: "The Witness", season: 2, episode: 3,
        year: 1995, duration: "47 min",
        description: "A key witness to a mob killing needs protection and only Fraser can provide it.",
        archiveId: "due-south-1994-98", archiveIndex: 25,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e04", title: "Bird in the Hand", season: 2, episode: 4,
        year: 1995, duration: "47 min",
        description: "A political assassination plot puts Fraser and Vecchio in the crosshairs.",
        archiveId: "due-south-1994-98", archiveIndex: 26,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e05", title: "The Promise", season: 2, episode: 5,
        year: 1995, duration: "47 min",
        description: "Fraser fulfils an old promise to a dying man, leading to unexpected danger.",
        archiveId: "due-south-1994-98", archiveIndex: 27,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e06", title: "The Mask", season: 2, episode: 6,
        year: 1995, duration: "47 min",
        description: "A stolen Native Canadian ceremonial mask becomes the centre of an international theft ring.",
        archiveId: "due-south-1994-98", archiveIndex: 28,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e07", title: "Juliet Is Bleeding", season: 2, episode: 7,
        year: 1995, duration: "47 min",
        description: "Vecchio's sister gets involved with a mob boss, forcing the team into a dangerous operation.",
        archiveId: "due-south-1994-98", archiveIndex: 29,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e08", title: "One Good Man", season: 2, episode: 8,
        year: 1995, duration: "47 min",
        description: "A politician's good intentions are exploited by those around him.",
        archiveId: "due-south-1994-98", archiveIndex: 30,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e09", title: "The Edge", season: 2, episode: 9,
        year: 1996, duration: "47 min",
        description: "Fraser confronts his own mortality after a near-death experience.",
        archiveId: "due-south-1994-98", archiveIndex: 31,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e10", title: "Starman", season: 2, episode: 10,
        year: 1996, duration: "47 min",
        description: "A high-profile astronaut is targeted by saboteurs and only Fraser sees through the deception.",
        archiveId: "due-south-1994-98", archiveIndex: 32,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e11", title: "We Are the Eggmen", season: 2, episode: 11,
        year: 1996, duration: "47 min",
        description: "An unusual case involving exotic eggs leads Fraser and Vecchio into a world of rare-animal smuggling.",
        archiveId: "due-south-1994-98", archiveIndex: 33,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e12", title: "Some Like It Red", season: 2, episode: 12,
        year: 1996, duration: "47 min",
        description: "Fraser goes undercover in the fashion world to catch a jewel thief.",
        archiveId: "due-south-1994-98", archiveIndex: 34,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e13", title: "White Men Can't Jump to Conclusions", season: 2, episode: 13,
        year: 1996, duration: "47 min",
        description: "A basketball charity event becomes the cover for a deadly scheme.",
        archiveId: "due-south-1994-98", archiveIndex: 35,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e14", title: "All the Queen's Horses", season: 2, episode: 14,
        year: 1996, duration: "47 min",
        description: "Fraser must prevent a hijacking of a train carrying the RCMP Musical Ride horses.",
        archiveId: "due-south-1994-98", archiveIndex: 36,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e15", title: "Body Language", season: 2, episode: 15,
        year: 1996, duration: "47 min",
        description: "A mute street artist communicates the only way he can — through art — to expose a killer.",
        archiveId: "due-south-1994-98", archiveIndex: 37,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e16", title: "The Duel", season: 2, episode: 16,
        year: 1996, duration: "47 min",
        description: "An honour dispute escalates into a life-or-death standoff.",
        archiveId: "due-south-1994-98", archiveIndex: 38,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e17", title: "Red, White or Blue", season: 2, episode: 17,
        year: 1996, duration: "47 min",
        description: "A retired spy's past catches up with him — and with Fraser.",
        archiveId: "due-south-1994-98", archiveIndex: 39,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s02e18", title: "Flashback", season: 2, episode: 18,
        year: 1996, duration: "47 min",
        description: "Fraser and Vecchio investigate a cold case using recovered memories.",
        archiveId: "due-south-1994-98", archiveIndex: 40,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      /* ── Season 3 ── */
      {
        id: "ds-s03e01", title: "Burning Down the House", season: 3, episode: 1,
        year: 1997, duration: "47 min",
        description: "In the season opener Fraser faces the aftermath of a conspiracy that shook the 27th District.",
        archiveId: "due-south-1994-98", archiveIndex: 41,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e02", title: "Eclipse", season: 3, episode: 2,
        year: 1997, duration: "47 min",
        description: "A solar eclipse coincides with a string of crimes that seem to defy explanation.",
        archiveId: "due-south-1994-98", archiveIndex: 42,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e03", title: "I Coulda Been a Defendant", season: 3, episode: 3,
        year: 1997, duration: "47 min",
        description: "Fraser finds himself on the wrong side of the law when he is accused of a crime.",
        archiveId: "due-south-1994-98", archiveIndex: 43,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e04", title: "Strange Bedfellows", season: 3, episode: 4,
        year: 1997, duration: "47 min",
        description: "Political rivals must cooperate to survive — and Fraser is the unlikely mediator.",
        archiveId: "due-south-1994-98", archiveIndex: 44,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e05", title: "Seeing Is Believing", season: 3, episode: 5,
        year: 1997, duration: "47 min",
        description: "Witnesses to a crime all report wildly different versions of events.",
        archiveId: "due-south-1994-98", archiveIndex: 45,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e06", title: "Bounty Hunter", season: 3, episode: 6,
        year: 1997, duration: "47 min",
        description: "A bounty hunter and Fraser clash over the retrieval of a fugitive.",
        archiveId: "due-south-1994-98", archiveIndex: 46,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e07", title: "Mountie & Soul", season: 3, episode: 7,
        year: 1997, duration: "47 min",
        description: "Fraser's sense of duty is tested when he must choose between regulation and justice.",
        archiveId: "due-south-1994-98", archiveIndex: 47,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e08", title: "Spy vs. Spy", season: 3, episode: 8,
        year: 1997, duration: "47 min",
        description: "Cold War secrets surface in Chicago when rival intelligence agents converge on the city.",
        archiveId: "due-south-1994-98", archiveIndex: 48,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e09", title: "Asylum", season: 3, episode: 9,
        year: 1997, duration: "47 min",
        description: "A defector seeks sanctuary at the Canadian Consulate, putting Fraser in a diplomatic minefield.",
        archiveId: "due-south-1994-98", archiveIndex: 49,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e10", title: "Perfect Strangers", season: 3, episode: 10,
        year: 1997, duration: "47 min",
        description: "Fraser and his new partner must work together despite their very different approaches.",
        archiveId: "due-south-1994-98", archiveIndex: 50,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e11", title: "Dead Guy Running", season: 3, episode: 11,
        year: 1997, duration: "47 min",
        description: "A man believed dead turns up alive — and very much in danger.",
        archiveId: "due-south-1994-98", archiveIndex: 51,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e12", title: "Mountie on the Bounty (Part 1)", season: 3, episode: 12,
        year: 1998, duration: "47 min",
        description: "Fraser and his partner chase a criminal onto a cargo ship bound for the open sea.",
        archiveId: "due-south-1994-98", archiveIndex: 52,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s03e13", title: "Mountie on the Bounty (Part 2)", season: 3, episode: 13,
        year: 1998, duration: "47 min",
        description: "Trapped at sea, Fraser must outwit the criminals and find a way back to shore.",
        archiveId: "due-south-1994-98", archiveIndex: 53,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      /* ── Season 4 ── */
      {
        id: "ds-s04e01", title: "Dr. Longball", season: 4, episode: 1,
        year: 1998, duration: "47 min",
        description: "A celebrity doctor's charity golf tournament turns deadly.",
        archiveId: "due-south-1994-98", archiveIndex: 54,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e02", title: "Easy Money", season: 4, episode: 2,
        year: 1998, duration: "47 min",
        description: "Fraser investigates a get-rich-quick scheme that is leaving victims in its wake.",
        archiveId: "due-south-1994-98", archiveIndex: 55,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e03", title: "The Ladies' Man", season: 4, episode: 3,
        year: 1998, duration: "47 min",
        description: "A charming con artist is targeting wealthy women across Chicago.",
        archiveId: "due-south-1994-98", archiveIndex: 56,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e04", title: "Mojo Rising", season: 4, episode: 4,
        year: 1998, duration: "47 min",
        description: "A blues musician's lucky charm is stolen — along with the evidence in a murder case.",
        archiveId: "due-south-1994-98", archiveIndex: 57,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e05", title: "Dead Men Don't Throw Rice", season: 4, episode: 5,
        year: 1998, duration: "47 min",
        description: "A wedding party becomes the scene of a crime when the groom is found dead.",
        archiveId: "due-south-1994-98", archiveIndex: 58,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e06", title: "Odds", season: 4, episode: 6,
        year: 1998, duration: "47 min",
        description: "Illegal gambling connects a series of seemingly unrelated crimes.",
        archiveId: "due-south-1994-98", archiveIndex: 59,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e07", title: "Mountie Sings the Blues", season: 4, episode: 7,
        year: 1998, duration: "47 min",
        description: "Fraser goes undercover in the Chicago blues scene to catch a killer.",
        archiveId: "due-south-1994-98", archiveIndex: 60,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e08", title: "Good for the Soul", season: 4, episode: 8,
        year: 1998, duration: "47 min",
        description: "A priest's confession puts Fraser in an impossible ethical position.",
        archiveId: "due-south-1994-98", archiveIndex: 61,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e09", title: "A Likely Story", season: 4, episode: 9,
        year: 1998, duration: "47 min",
        description: "An improbable chain of coincidences leads Fraser to the truth in a baffling case.",
        archiveId: "due-south-1994-98", archiveIndex: 62,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e10", title: "Say Amen", season: 4, episode: 10,
        year: 1998, duration: "47 min",
        description: "A revival preacher is suspected of fraud — or something far worse.",
        archiveId: "due-south-1994-98", archiveIndex: 63,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e11", title: "Hunting Season", season: 4, episode: 11,
        year: 1998, duration: "47 min",
        description: "A dangerous game of cat and mouse unfolds across the city.",
        archiveId: "due-south-1994-98", archiveIndex: 64,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e12", title: "Call of the Wild (Part 1)", season: 4, episode: 12,
        year: 1998, duration: "47 min",
        description: "Fraser is drawn back to Canada as a series finale adventure begins.",
        archiveId: "due-south-1994-98", archiveIndex: 65,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
      {
        id: "ds-s04e13", title: "Call of the Wild (Part 2)", season: 4, episode: 13,
        year: 1998, duration: "47 min",
        description: "Fraser's final adventure concludes, bringing his journey full circle.",
        archiveId: "due-south-1994-98", archiveIndex: 66,
        thumbnail: "https://archive.org/services/img/due-south-1994-98",
      },
    ],
  },

  {
    id: "mash",
    title: "M*A*S*H",
    years: "1972–1983",
    genre: ["Drama", "Comedy", "War"],
    rating: "TV-PG",
    score: 9.1,
    description:
      "The staff of a mobile army surgical hospital during the Korean War deal with the horrors of battle through humor and camaraderie.",
    thumbnail: "https://archive.org/services/img/MashTVShow",
    featured: true,
    episodes: [
      {
        id: "mash-s01e01",
        title: "Pilot",
        season: 1,
        episode: 1,
        year: 1972,
        duration: "25 min",
        description: "Hawkeye and Trapper devise a scheme to raise money for a Korean orphan.",
        archiveId: "MASH_s01e01",
        thumbnail: "https://archive.org/services/img/MashTVShow",
      },
      {
        id: "mash-s01e02",
        title: "To Market, To Market",
        season: 1,
        episode: 2,
        year: 1972,
        duration: "25 min",
        description: "Henry trades the camp's hydrocort for a black market still.",
        archiveId: "MASH_s01e02",
        thumbnail: "https://archive.org/services/img/MashTVShow",
      },
    ],
  },
  {
    id: "all-in-the-family",
    title: "All in the Family",
    years: "1971–1979",
    genre: ["Comedy", "Drama"],
    rating: "TV-PG",
    score: 8.9,
    description:
      "Archie Bunker, a working-class bigot living in Queens, New York, clashes with his liberal son-in-law.",
    thumbnail: "https://archive.org/services/img/AllInTheFamily",
    featured: false,
    episodes: [
      {
        id: "aitf-s01e01",
        title: "Meet the Bunkers",
        season: 1,
        episode: 1,
        year: 1971,
        duration: "25 min",
        description: "Archie and Edith return home to find that Mike and Gloria have celebrated their anniversary without them.",
        archiveId: "AllInTheFamily_s01e01",
        thumbnail: "https://archive.org/services/img/AllInTheFamily",
      },
    ],
  },
  {
    id: "cheers",
    title: "Cheers",
    years: "1982–1993",
    genre: ["Comedy"],
    rating: "TV-PG",
    score: 9.0,
    description:
      "The regulars of Cheers, a Boston bar, deal with their relationships and quirky personalities.",
    thumbnail: "https://archive.org/services/img/CheersTV",
    featured: true,
    episodes: [
      {
        id: "cheers-s01e01",
        title: "Give Me a Ring Sometime",
        season: 1,
        episode: 1,
        year: 1982,
        duration: "25 min",
        description: "Diane Chambers ends up working at Cheers after being left by her fiancé.",
        archiveId: "Cheers_s01e01",
        thumbnail: "https://archive.org/services/img/CheersTV",
      },
    ],
  },
  {
    id: "the-twilight-zone",
    title: "The Twilight Zone",
    years: "1959–1964",
    genre: ["Drama", "Sci-Fi", "Fantasy"],
    rating: "TV-PG",
    score: 9.0,
    description:
      "Anthology series of tales of the unusual, the unexpected, and the macabre.",
    thumbnail: "https://archive.org/services/img/twilightzone",
    featured: true,
    episodes: [
      {
        id: "tz-s01e01",
        title: "Where Is Everybody?",
        season: 1,
        episode: 1,
        year: 1959,
        duration: "25 min",
        description: "A man finds himself in a small town completely devoid of any other people.",
        archiveId: "the.twilight.zone.s01e01",
        thumbnail: "https://archive.org/services/img/twilightzone",
      },
      {
        id: "tz-s01e16",
        title: "The Hitch-Hiker",
        season: 1,
        episode: 16,
        year: 1960,
        duration: "25 min",
        description: "A young woman is terrorized by a mysterious hitchhiker who appears no matter how far she drives.",
        archiveId: "TheTwilightZone-TheHitch-hiker",
        thumbnail: "https://archive.org/services/img/twilightzone",
      },
    ],
  },
  {
    id: "star-trek",
    title: "Star Trek: The Original Series",
    years: "1966–1969",
    genre: ["Sci-Fi", "Adventure"],
    rating: "TV-G",
    score: 8.4,
    description:
      "Captain Kirk and the crew of the Enterprise explore the galaxy in the 23rd century.",
    thumbnail: "https://archive.org/services/img/StarTrekOriginalSeries",
    featured: false,
    episodes: [
      {
        id: "tos-s01e01",
        title: "The Man Trap",
        season: 1,
        episode: 1,
        year: 1966,
        duration: "51 min",
        description: "A salt-craving creature capable of disguising itself preys on the Enterprise crew.",
        archiveId: "StarTrek_s01e01",
        thumbnail: "https://archive.org/services/img/StarTrekOriginalSeries",
      },
    ],
  },
  {
    id: "i-love-lucy",
    title: "I Love Lucy",
    years: "1951–1957",
    genre: ["Comedy"],
    rating: "TV-G",
    score: 8.9,
    description:
      "The misadventures of Lucy Ricardo and her husband Ricky, along with their best friends and landlords.",
    thumbnail: "https://archive.org/services/img/ILoveLucy",
    featured: false,
    episodes: [
      {
        id: "lucy-s01e01",
        title: "The Girls Want to Go to a Nightclub",
        season: 1,
        episode: 1,
        year: 1951,
        duration: "30 min",
        description: "Lucy and Ethel want to go to a nightclub for their anniversary but their husbands have other plans.",
        archiveId: "ILoveLucy_s01e01",
        thumbnail: "https://archive.org/services/img/ILoveLucy",
      },
    ],
  },
  {
    id: "the-andy-griffith-show",
    title: "The Andy Griffith Show",
    years: "1960–1968",
    genre: ["Comedy", "Drama"],
    rating: "TV-G",
    score: 8.7,
    description:
      "Sheriff Andy Taylor raises his son Opie in the fictional small town of Mayberry, North Carolina.",
    thumbnail: "https://archive.org/services/img/AndyGriffithShow",
    featured: false,
    episodes: [
      {
        id: "andy-s01e01",
        title: "The New Housekeeper",
        season: 1,
        episode: 1,
        year: 1960,
        duration: "25 min",
        description: "Andy's Aunt Bee arrives to take care of the Taylor household.",
        archiveId: "AndyGriffith_s01e01",
        thumbnail: "https://archive.org/services/img/AndyGriffithShow",
      },
    ],
  },
  {
    id: "leave-it-to-beaver",
    title: "Leave It to Beaver",
    years: "1957–1963",
    genre: ["Comedy", "Family"],
    rating: "TV-G",
    score: 8.1,
    description:
      "The adventures of the Cleaver family, particularly young Theodore 'Beaver' Cleaver.",
    thumbnail: "https://archive.org/services/img/LeaveItToBeaver",
    featured: false,
    episodes: [
      {
        id: "beaver-s01e01",
        title: "Beaver Gets 'Spelied'",
        season: 1,
        episode: 1,
        year: 1957,
        duration: "26 min",
        description: "Beaver tries to get out of a spelling test.",
        archiveId: "LeaveItToBeaver_s01e01",
        thumbnail: "https://archive.org/services/img/LeaveItToBeaver",
      },
    ],
  },
  {
    id: "seinfeld",
    title: "Seinfeld",
    years: "1989–1998",
    genre: ["Comedy"],
    rating: "TV-PG",
    score: 9.0,
    description:
      "The show about nothing follows Jerry Seinfeld and his group of quirky New York friends.",
    thumbnail: "https://archive.org/services/img/Seinfeld",
    featured: true,
    episodes: [
      {
        id: "sein-s01e01",
        title: "The Seinfeld Chronicles",
        season: 1,
        episode: 1,
        year: 1989,
        duration: "23 min",
        description: "Jerry awaits the arrival of a woman he met in Lansing to determine if she is his girlfriend.",
        archiveId: "Seinfeld_s01e01",
        thumbnail: "https://archive.org/services/img/Seinfeld",
      },
    ],
  },
  {
    id: "gilligans-island",
    title: "Gilligan's Island",
    years: "1964–1967",
    genre: ["Comedy", "Adventure"],
    rating: "TV-G",
    score: 7.3,
    description:
      "A group of castaways are stranded on a deserted island and try to find their way home.",
    thumbnail: "https://archive.org/services/img/GilligansIsland",
    featured: false,
    episodes: [
      {
        id: "gilligan-s01e01",
        title: "Two on a Raft",
        season: 1,
        episode: 1,
        year: 1964,
        duration: "25 min",
        description: "Gilligan and the Skipper set out on a raft to find help.",
        archiveId: "GilligansIsland_s01e01",
        thumbnail: "https://archive.org/services/img/GilligansIsland",
      },
    ],
  },
  {
    id: "the-brady-bunch",
    title: "The Brady Bunch",
    years: "1969–1974",
    genre: ["Comedy", "Family"],
    rating: "TV-G",
    score: 7.4,
    description:
      "A blended family navigates life together with six children and a helpful housekeeper.",
    thumbnail: "https://archive.org/services/img/TheBradyBunch",
    featured: false,
    episodes: [
      {
        id: "brady-s01e01",
        title: "The Honeymoon",
        season: 1,
        episode: 1,
        year: 1969,
        duration: "25 min",
        description: "Mike and Carol Brady prepare for their honeymoon while the kids adjust to their new family.",
        archiveId: "BradyBunch_s01e01",
        thumbnail: "https://archive.org/services/img/TheBradyBunch",
      },
    ],
  },
  {
    id: "columbo",
    title: "Columbo",
    years: "1971–2003",
    genre: ["Crime", "Drama", "Mystery"],
    rating: "TV-PG",
    score: 8.6,
    description:
      "A seemingly disheveled but brilliant L.A. police detective uses his humble demeanor to lull murderers into letting down their guard.",
    thumbnail: "https://archive.org/services/img/Columbo",
    featured: true,
    episodes: [
      {
        id: "columbo-s01e01",
        title: "Murder by the Book",
        season: 1,
        episode: 1,
        year: 1971,
        duration: "73 min",
        description: "Columbo investigates when a mystery writer murders his partner.",
        archiveId: "Columbo_MurderByTheBook",
        thumbnail: "https://archive.org/services/img/Columbo",
      },
    ],
  },
  {
    id: "the-mary-tyler-moore-show",
    title: "The Mary Tyler Moore Show",
    years: "1970–1977",
    genre: ["Comedy", "Drama"],
    rating: "TV-G",
    score: 8.1,
    description:
      "Mary Richards moves to Minneapolis and starts working at a TV news station, navigating single life and career.",
    thumbnail: "https://archive.org/services/img/MaryTylerMoore",
    featured: false,
    episodes: [
      {
        id: "mtm-s01e01",
        title: "Love Is All Around",
        season: 1,
        episode: 1,
        year: 1970,
        duration: "25 min",
        description: "Mary Richards arrives in Minneapolis and lands a job at WJM-TV.",
        archiveId: "MaryTylerMoore_s01e01",
        thumbnail: "https://archive.org/services/img/MaryTylerMoore",
      },
    ],
  },
  {
    id: "happy-days",
    title: "Happy Days",
    years: "1974–1984",
    genre: ["Comedy", "Drama"],
    rating: "TV-G",
    score: 7.4,
    description:
      "Set in 1950s Milwaukee, the Cunningham family and their friend Fonzie experience life in the golden age of rock and roll.",
    thumbnail: "https://archive.org/services/img/HappyDays",
    featured: false,
    episodes: [
      {
        id: "happydays-s01e01",
        title: "All the Way",
        season: 1,
        episode: 1,
        year: 1974,
        duration: "25 min",
        description: "Richie Cunningham tries to prove himself at the drive-in.",
        archiveId: "HappyDays_s01e01",
        thumbnail: "https://archive.org/services/img/HappyDays",
      },
    ],
  },
  {
    id: "the-price-is-right",
    title: "The Price Is Right",
    years: "1972–present",
    genre: ["Game Show"],
    rating: "TV-G",
    score: 7.6,
    description:
      "Contestants compete by trying to correctly price merchandise to win cash and prizes.",
    thumbnail: "https://archive.org/services/img/ThePriceIsRight",
    featured: false,
    episodes: [
      {
        id: "tpir-s01e01",
        title: "Premiere Episode",
        season: 1,
        episode: 1,
        year: 1972,
        duration: "60 min",
        description: "The first episode of the long-running game show hosted by Bob Barker.",
        archiveId: "ThePriceIsRight_premiere",
        thumbnail: "https://archive.org/services/img/ThePriceIsRight",
      },
    ],
  },
  /* ────────────────────────────────────────────────────────────
     SPACECAMP  (1986)
     Single feature film — archive identifier: kids-space-camp-1986-family-comedy
     ──────────────────────────────────────────────────────────── */
  {
    id: "spacecamp-1986",
    type: "movie",
    title: "SpaceCamp",
    years: "1986",
    genre: ["Adventure", "Comedy", "Family", "Sci-Fi"],
    rating: "PG",
    score: 6.5,
    description:
      "A group of teenagers attending NASA's U.S. Space Camp in Huntsville, Alabama are accidentally launched into orbit aboard the Space Shuttle Atlantis. Guided by their instructor, the unlikely crew must use their training to survive and find a way back to Earth. Stars Kate Capshaw, Lea Thompson, and a young Joaquin Phoenix.",
    thumbnail: "https://archive.org/services/img/kids-space-camp-1986-family-comedy",
    featured: true,
    episodes: [
      {
        id: "spacecamp-1986-full",
        title: "SpaceCamp",
        season: 0,
        episode: 0,
        year: 1986,
        duration: "107 min",
        description:
          "A group of young Space Camp attendees are accidentally launched into orbit aboard the Space Shuttle Atlantis and must rely on their training to return safely to Earth.",
        archiveId: "kids-space-camp-1986-family-comedy",
        thumbnail: "https://archive.org/services/img/kids-space-camp-1986-family-comedy",
      },
    ],
  },
];

const CATEGORIES = [
  { id: "featured", label: "Featured Classics" },
  { id: "drama", label: "Drama" },
  { id: "comedy", label: "Comedy" },
  { id: "sci-fi", label: "Sci-Fi & Fantasy" },
  { id: "crime", label: "Crime & Mystery" },
  { id: "family", label: "Family" },
  { id: "1970s", label: "1970s Favorites" },
  { id: "1980s", label: "1980s Hits" },
  { id: "1990s", label: "1990s Classics" },
  { id: "movies", label: "Classic Movies" },
];

function getShowsByGenre(genre) {
  return SHOWS.filter((s) => s.genre.some((g) => g.toLowerCase() === genre.toLowerCase()));
}

function getFeaturedShows() {
  return SHOWS.filter((s) => s.featured);
}

function getMovies() {
  return SHOWS.filter((s) => s.type === "movie");
}

function getShowsByDecade(decade) {
  const start = parseInt(decade);
  return SHOWS.filter((s) => {
    const startYear = parseInt(s.years.split("–")[0]);
    return startYear >= start && startYear < start + 10;
  });
}

function getShowById(id) {
  return SHOWS.find((s) => s.id === id);
}
