(function(){
"use strict";
const SEARCH="https://archive.org/advancedsearch.php",META="https://archive.org/metadata/";
const INVENTORY="starquest.game.inventory.v1",RECEIPTS="starquest.game.reward.receipts.v1";
const systems={nes:{core:"nes",ext:/\.(nes)$/i},snes:{core:"snes",ext:/\.(sfc|smc)$/i},gb:{core:"gb",ext:/\.(gb)$/i},gba:{core:"gba",ext:/\.(gba)$/i},genesis:{core:"segaMD",ext:/\.(md|gen|bin)$/i},n64:{core:"n64",ext:/\.(z64|n64|v64)$/i},psx:{core:"psx",ext:/\.(cue|chd|pbp)$/i}};
const $=id=>document.getElementById(id);let current=null,playTimer=null;
function clean(v,n){return String(Array.isArray(v)?v.join(", "):v||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,n)}
function licensed(meta){const m=meta.metadata||{};const evidence=clean([m.licenseurl,m.rights,m.subject,m.description],1600);return /creativecommons|public domain|homebrew|freeware|open source|authorized for distribution/i.test(evidence)}
function params(q,system){const term=clean(q,100).replace(/[^a-zA-Z0-9 '-]/g," ");const p=new URLSearchParams({q:["mediatype:software","("+term+")","(subject:homebrew OR subject:\"public domain\" OR licenseurl:*creativecommons.org*)"].join(" AND "),rows:"20",output:"json"});["identifier","title","year","description","subject","licenseurl"].forEach(f=>p.append("fl[]",f));p.append("sort[]","downloads desc");return SEARCH+"?"+p}
function direct(id,name){return "https://archive.org/download/"+encodeURIComponent(id)+"/"+String(name).split("/").map(encodeURIComponent).join("/")}
async function verify(doc,system){const id=clean(doc.identifier,180);const r=await fetch(META+encodeURIComponent(id),{credentials:"omit",referrerPolicy:"no-referrer"});if(!r.ok)return null;const meta=await r.json();if(meta.is_dark||meta.metadata?.access_restricted_item==="true"||!licensed(meta))return null;const spec=systems[system];const files=(meta.files||[]).filter(f=>spec.ext.test(String(f.name||""))&&f.private!==true&&f.private!=="true"&&!/demo|sample|bios/i.test(String(f.name||"")));if(!files.length)return null;files.sort((a,b)=>(Number(b.size)||0)-(Number(a.size)||0));return{id,title:clean(doc.title,120)||id,year:clean(doc.year,12),system,file:files[0].name,license:clean([meta.metadata?.licenseurl,meta.metadata?.rights],500),thumb:"https://archive.org/services/img/"+encodeURIComponent(id)}}
function save(game){let list=[];try{list=JSON.parse(localStorage.getItem(INVENTORY)||"[]")}catch(_){};list=(Array.isArray(list)?list:[]).filter(x=>x.id!==game.id);list.push(game);localStorage.setItem(INVENTORY,JSON.stringify(list.slice(-100)))}
function render(g){const a=document.createElement("article");a.className="game";const img=document.createElement("img");img.src=g.thumb;img.alt="";const box=document.createElement("div");const h=document.createElement("h3");h.textContent=g.title;const p=document.createElement("p");p.textContent=(g.year||"Archive")+" · "+g.system.toUpperCase()+" · license evidence recorded";const b=document.createElement("button");b.className="primary";b.textContent="Deploy & play";b.onclick=()=>deploy(g);box.append(h,p,b);a.append(img,box);return a}
async function search(){const q=$("query").value.trim(),system=$("system").value;$("status").textContent="Checking Archive records and license evidence…";$("results").innerHTML="";try{const r=await fetch(params(q,system),{credentials:"omit",referrerPolicy:"no-referrer"});const docs=(await r.json()).response?.docs||[];const found=[];for(const d of docs){if(found.length>=8)break;const g=await verify(d,system).catch(()=>null);if(g)found.push(g)}found.forEach(g=>$("results").appendChild(render(g)));$("status").textContent=found.length?found.length+" authorized/open ROM source(s) verified.":"No ROMs passed source and license verification."}catch(e){$("status").textContent="Game source search is temporarily unavailable."}}
function loadCore(g){window.EJS_player="#game";window.EJS_core=systems[g.system].core;window.EJS_gameUrl=direct(g.id,g.file);window.EJS_gameName=g.title;window.EJS_pathtodata="https://cdn.emulatorjs.org/stable/data/";window.EJS_startOnLoaded=true;const old=document.getElementById("ejs-loader");if(old)old.remove();const s=document.createElement("script");s.id="ejs-loader";s.src="https://cdn.emulatorjs.org/stable/data/loader.js";document.body.appendChild(s)}
function addHalf(kind,g){let state={units:0,ids:{},events:[]};try{state=Object.assign(state,JSON.parse(localStorage.getItem(RECEIPTS)||"{}"))}catch(_){};const day=new Date().toISOString().slice(0,10),id=kind+":"+g.id+":"+day;if(state.ids[id])return false;state.ids[id]=Date.now();state.units=(Number(state.units)||0)+1;state.events.push({id,kind,gameId:g.id,title:g.title,amount:0.05,source:"client_receipt",payoutStatus:"pending_contract_settlement",at:Date.now()});let minted=0;while(state.units>=20){state.units-=20;minted++;if(window.StarQuestAuth)window.StarQuestAuth.addTokens(1,"Game activity reward: twenty .05 receipts",id,"game_reward")}state.events=state.events.slice(-300);localStorage.setItem(RECEIPTS,JSON.stringify(state));$("receipt").textContent="+.05 "+kind+" receipt · "+state.units+"/20 toward next StarCoin"+(minted?" · StarCoin minted!":"");return true}
function deploy(g){current=g;save(g);$("empty").hidden=true;$("game").hidden=false;$("share").disabled=false;const c=$("controller");c.dataset.system=g.system;c.classList.add("active");$("stage").classList.remove("minimized");$("status").textContent="Loading "+g.title+"…";loadCore(g);clearTimeout(playTimer);playTimer=setTimeout(()=>addHalf("qualified_play",g),300000)}
async function share(){if(!current)return;const url=location.href.split("#")[0]+"#game="+encodeURIComponent(current.id),data={title:current.title,text:"Play "+current.title+" in StarQuest Game Deck",url};try{if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(url);addHalf("confirmed_share",current)}catch(_){}}
$("search").onclick=search;$("query").onkeydown=e=>{if(e.key==="Enter")search()};$("share").onclick=share;$("full").onclick=()=>$("stage").requestFullscreen?.();$("mini").onclick=()=>$("stage").classList.toggle("minimized");
})();